import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d5e7d8",
        "surface-tint": "#496457",
        "primary-container": "#0d281d",
        "tertiary": "#000b2c",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#003ea7",
        "inverse-on-surface": "#e3f5e6",
        "on-secondary-container": "#007437",
        "surface-container-high": "#dbedde",
        "surface-dim": "#ccdfd0",
        "primary-fixed-dim": "#afcdbd",
        "on-tertiary-container": "#5784fc",
        "tertiary-fixed-dim": "#b4c5ff",
        "surface": "#ecfeef",
        "on-background": "#101f16",
        "primary": "#001109",
        "on-tertiary-fixed": "#00174b",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#dbe1ff",
        "surface-bright": "#ecfeef",
        "on-surface": "#101f16",
        "on-surface-variant": "#424844",
        "tertiary-container": "#001e5b",
        "secondary-container": "#8ff9a7",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#727974",
        "secondary-fixed-dim": "#73dc8d",
        "error": "#ba1a1a",
        "primary-fixed": "#cbead8",
        "on-primary-container": "#749182",
        "secondary": "#006d33",
        "on-secondary-fixed": "#00210b",
        "on-primary-fixed-variant": "#324c40",
        "outline-variant": "#c2c8c2",
        "surface-container-low": "#e6f8e9",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#e0f2e4",
        "background": "#ecfeef",
        "inverse-surface": "#24342a",
        "surface-container-highest": "#d5e7d8",
        "on-error": "#ffffff",
        "on-primary-fixed": "#052016",
        "secondary-fixed": "#8ff9a7",
        "inverse-primary": "#afcdbd",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#005225",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "xs": "8px",
        "lg": "24px",
        "md": "16px",
        "grid-gutter": "20px",
        "container-margin": "40px",
        "base": "4px",
        "sm": "12px",
        "xl": "32px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "h2": ["Sora"],
        "h3": ["Sora"],
        "label-caps": ["Inter"],
        "status-tag": ["Inter"],
        "h1": ["Sora"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "sans": ["Inter", "Sora"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "h2": ["32px", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h3": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "status-tag": ["13px", { lineHeight: "1", fontWeight: "500" }],
        "h1": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [forms],
};
